spring:
  datasource:
    url: ${db.url:jdbc:postgresql://localhost/app}
    username: ${db.username:root}
    password: ${db.password:123}
  mustache:
    expose-request-attributes: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebook.client-id}
            client-secret: ${facebook.client-secret}
        provider:
          facebook:
            user-name-attribute: email

server:
  forward-headers-strategy: framework